# Generated by Django 4.2.1 on 2023-05-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PredictorMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ia", models.FloatField()),
                ("ib", models.FloatField()),
                ("ic", models.FloatField()),
                ("va", models.FloatField()),
                ("vb", models.FloatField()),
                ("vc", models.FloatField()),
                ("ans", models.FloatField()),
            ],
        ),
    ]
