# Generated by Django 4.2.1 on 2023-05-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_rename_predictormode_predictormodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="predictormodel",
            name="ans",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
