# Generated by Django 4.2.1 on 2023-05-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_predictormodel_ans"),
    ]

    operations = [
        migrations.CreateModel(
            name="GuideLines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                ("guide_line", models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name="predictormodel",
            old_name="ans",
            new_name="fault_type",
        ),
    ]
